# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eedcaf33f94c9e4330fa3fb5d90a48579af7c2e1c7d640a1e62b253460521ee3bf0832d0b77766ab5f25c7dd8a51c62b3198c9e7032c66dbea83068200e38872

test:
  secret_key_base: 3653c853d9149a2fc74244f8a5fefe0a45bf98386f9586492c469e1416e076ce8de9d7a1172bf1293ed65437b165009f8bfcff0ebe50461e13dcda10cc067fcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
